baseurl = "/"
languageCode = "pt-br"
title = "Textos, ideias e tutoriais de uma mente bagunçada."
theme = "hugo-nederburg-theme"
googleAnalytics = "UA-117053218-2"
disqusShortname = "gburin"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:slug/"

# Nav links in the side bar
[[params.navlinks]]
name = "Sobre"
url = "about/"

[params.social]
email         = "arietebio@gmail.com"
twitter       = "https://www.twitter.com/gustavoburin"
instagram     = "https://www.instagram.com/gburin_ari"
github        = "https://www.github.com/gburin"

[params]
    description = "Um blog para registrar ideias, reflexões e tutoriais."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["R", "r", "yaml"]
    highlightjsTheme = "zenburn"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

